### PR TITLE
Hyper 0.12, new Tokio runtime

### PR DESCRIPTION
**Pull request by pimeys**
Ok, time for some maintenance. This PR includes:

* Upgrade for the upcoming Hyper 0.12, which will be released quite soon and includes countless performance fixes, bugfixes, cleanups and new features. We want the performance, so we'll follow Hyper's development :)
* Removes `Cargo.lock` from the library. The preferred way is to define library versions in `Cargo.toml` and let the users update their setup with `cargo update`.
* Removes dependency for deprecated `tokio-core`. The preferred way is to use the `tokio` crate and its runtime.

This will break things a bit. The headers system is completely changed from the old types to the new `http` crate. RetryAfter is no more, so I replicated the functionality with `chrono`.

The `Client` no longer requires a `Handle` so we can leave it out from the API.

This can be merged to master, release to crates.io can happen when Hyper 0.12 is released. The major version should go up to 0.3.0 due to breaking changes.

---
This change is [Reviewable](https://reviewable.io/reviews/panicbit/fcm-rust/8)

### CODE REVIEW

**Comment by panicbit** [comment]
Nice! :+1:

Are you interested in taking ownership of the crate?
(I don't have a lot of interest in FCM at the moment :disappointed:)

**Comment by panicbit** [comment]
In fact, you are already owner! Feel free to change the crate metadata to point to your repo and release as you see fit!

**Comment by pimeys** [comment]
Hey, can I get the ownership to the crates.io domain so I can publish new versions? Our company will create an open source organization to github later this summer, so we could take ownership of this crate including my a2 and web-push crates.

**Comment by panicbit** [comment]
You should already be able to publish new versions!

**Pull request merged**
