### PR TITLE
Async version using Tokio

### PR DESCRIPTION
**Pull request by pimeys**
Hi,

I don't know how much alive your version of `fcm-rust` is, but here's our changes since the summer to make it asynchronious and adding support to some missing things like the `Retry-After` header. I can't say does it make sense for you to merge this or should we rename mine to be `tokio-fcm` and me authoring this new library. I pretty much broke the API here so it's a major change.

We've been pushing huge amount of notifications with this library and the not-yet-released `tokio-hyper`. We could be faster if not allocating so much, but that has not been an issue for us yet.

What do you think, are you still maintaining your branch?

---
This change is [Reviewable](https://reviewable.io/reviews/panicbit/fcm-rust/1)

### CODE REVIEW

**Comment by panicbit** [comment]
I didn't touch this fork in a while and I don't have any projects that depend on this fork. I also don't know of any other projects depending on it (I didn't research though).
It should be no problem to merge this and bump the crate's major version because of the API break.
If you wish to help maintain this I would give you commit access and/or add you as maintainer on crates.io.
I will review this PR in a few hours :)

**Comment by pimeys** [comment]
We have to wait for a while. The tokio version of hyper is not stable yet and might change. We depend on it from github currently and I guess we can merge this to your branch and release it into crates when hyper-tokio (version 0.11.0) is out.

I know at least that the body handling will change, so it will definitely break this before being stable. Anyways we serve hundreds of thousands of notifications per minute using my fork now and it's definitely way faster than the sync version with small amount of threads.

I need to be able to maintain this, so you can add me as a maintainer!

**Comment by pimeys** [comment]
Merged this and bumped the version to 0.2.0. Hyper-tokio is stable and this is now ready to crates.io.

Few problems:

- I don't have the right to push it to crates.io
- The documentation doesn't seem to update. You do this a bit differently than I do usually, so I don't see why the travis build doesn't generate the new docs.

**Comment by panicbit** [comment]
Hey, thanks!

I'll push an updated version to crates.io and check out why the docs won't update.

**Comment by panicbit** [comment]
- Published `v0.2.0` on crates.io
- Added you as owner
- Fixed [doc](https://panicbit.github.io/fcm-rust/fcm/index.html) upload (I might have accidentally deleted the github token)
- :tada:

**Comment by pimeys** [comment]
Ok, I'll switch our production systems to use the official crate!

**Comment by pimeys** [comment]
Uhm, one more thing! Should we open up the issues for this crate? It's quite different from the original GCM crate, which still keeps on living...

**Comment by panicbit** [comment]
Oh definitely! I wasn't aware that they are disabled.

**Pull request merged**
